version: '3.9'
services:
  mongo:
    restart: always
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    networks:
      - figure-network

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    networks:
      - figure-network
    depends_on:
      - mongo

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # stdin_open: true
    # tty: true
    env_file:
      - ./env/frontend.env
    networks:
      - figure-network
    depends_on:
      - mongo
      - backend

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - figure-network
    depends_on:
      - mongo
      - backend
      - frontend

volumes:
  data:

networks:
  figure-network:
    driver: bridge
