version: '3.9'
services:
  mongo:
    restart: always
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    networks:
      - figure-network

  backend:
    restart: always
    container_name: backend
    image: index.docker.io/starlightromero/figure-backend
    env_file:
      - ./env/backend.env
    networks:
      - figure-network
    depends_on:
      - mongo

  frontend:
    restart: always
    container_name: frontend
    image: index.docker.io/starlightromero/figure-frontend
    env_file:
      - ./env/frontend.env
    networks:
      - figure-network
    depends_on:
      - mongo
      - backend

  nginx:
    restart: always
    container_name: nginx
    image: index.docker.io/starlightromero/figure-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - figure-network
    depends_on:
      - mongo
      - backend
      - frontend

volumes:
  data:

networks:
  figure-network:
    driver: bridge
